source "${HOME}/.config/zsh/source.zsh"
source "${HOME}/.config/zsh/scripts.zsh"
source "${HOME}/.config/zsh/environment.zsh"
source "${HOME}/.config/zsh/history.zsh"
source "${HOME}/.config/zsh/alias.zsh"
source "${HOME}/.config/zsh/zinit.zsh"
