local builtin = require('telescope.builtin')
local custom = require('plugins.telescope.setup')
local telescope = require('telescope')
local utils = require('telescope.utils')

vim.keymap.set('n', '<leader>ff', function() builtin.find_files({ hidden = true }) end)
vim.keymap.set('n', '<c-p>', function() builtin.git_files({ hidden = true }) end)
vim.keymap.set('n', '<leader>fw', function() builtin.grep_string({ search = vim.fn.input('🔎 ') }) end)
vim.keymap.set('n', '<leader>fb', function() builtin.buffers() end)
vim.keymap.set('n', '<leader>fh', function() builtin.help_tags() end)
vim.keymap.set('n', '<leader>fk', function() builtin.keymaps() end)
vim.keymap.set('n', '<leader>fp', function() custom.search_plugins() end)
vim.keymap.set('n', '<leader>fg', function() builtin.git_status() end)
vim.keymap.set('n', '<leader>fl', function() builtin.git_commits() end)
vim.keymap.set('n', '<leader>fn', function() builtin.treesitter() end)
vim.keymap.set('n', '<leader>fd', function() telescope.extensions.dap.list_breakpoints() end)

vim.keymap.set('n', '-', function()
  telescope.extensions.file_browser.file_browser({ cwd = utils.buffer_dir() })
end)
