vim.keymap.set("n", "<leader>gh", function()
	vim.api.nvim_command("DiffviewFileHistory %")
end)
vim.keymap.set("n", "<leader>gH", function()
	vim.api.nvim_command("DiffviewFileHistory")
end)
vim.keymap.set("n", "<leader>gd", function()
	vim.api.nvim_command("DiffviewOpen")
end)
