vim.keymap.set("n", "<leader>gs", function()
	vim.cmd("G")
end)
vim.keymap.set("n", "<leader>gc", function()
	vim.cmd("G commit")
end)
vim.keymap.set("n", "<leader>gf", function()
	vim.cmd("G fetch origin")
	vim.notify("✅ git fetched origin")
end)
vim.keymap.set("n", "<leader>gp", function()
	vim.cmd("G pull")
end)
vim.keymap.set("n", "<leader>gP", function()
	vim.cmd("G push --force-with-lease")
end)
vim.keymap.set("n", "<leader>gl", function()
	vim.cmd("G log")
end)
vim.keymap.set("n", "<leader>gh", function()
	vim.cmd("G log --stat %")
end)
vim.keymap.set("n", "<leader>gd", function()
	vim.cmd("G diff %")
end)
vim.keymap.set("n", "<leader>gD", function()
	vim.cmd("G diff")
end)
vim.keymap.set("n", "<leader>gb", function()
	vim.cmd("G blame")
end)
